[package]
name = "copybot-app"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
copybot-config = { path = "../config" }
copybot-core-types = { path = "../core-types" }
copybot-discovery = { path = "../discovery" }
copybot-ingestion = { path = "../ingestion" }
copybot-shadow = { path = "../shadow" }
copybot-execution = { path = "../execution" }
copybot-storage = { path = "../storage" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
