[package]
name = "copybot-discovery"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
copybot-config = { path = "../config" }
copybot-core-types = { path = "../core-types" }
copybot-storage = { path = "../storage" }
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
